/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: that1fungi (https://sketchfab.com/that1fungi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bb8-e30d0c2c465e4bd08c9359f28ccddc8b
title: BB8
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useScroll } from '../helpers/ScrollControls'

export default function Model({ ...props }) {
  const group = useRef()
  const body = useRef()
  const head = useRef()
  const scroll = useScroll()
  const { nodes, materials } = useGLTF('/bb8.gltf')
  
  useFrame((state,delta) => {
    const offset = scroll.offset
    body.current.rotation.z -= 0.001;
    group.current.position.set(Math.sin(offset) * 10/Math.sin(1), 0, Math.sin(offset) * -4/Math.sin(1))
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group ref={body} position={[-1.04, -0.13, 0]} scale={1} rotation={[0,0,0]}>
            <group position={[0, 0, 0]} rotation={[0.85, -0.77, 0.22]} scale={1}>
              <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
            </group>
          </group>
          <group ref={head} position={[-1.04, -0.13, 0]} rotation={[-0.18, 0.53, 0.19]}>
            <group position={[-0.02, 1.37, 0.44]} rotation={[1.05, 0, 0]} scale={0.16}>
              <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.26, 1.22, 0.48]} rotation={[1.34, 0.24, -0.46]} scale={0.1}>
              <mesh geometry={nodes.Object_9.geometry} material={materials['Material.002']} />
              <mesh geometry={nodes.Object_10.geometry} material={materials['Material.003']} />
              <mesh geometry={nodes.Object_11.geometry} material={materials['Material.005']} />
            </group>
            <group position={[-0.02, 1.59, -0.24]} scale={[0.02, 0.07, 0.02]}>
              <mesh geometry={nodes.Object_13.geometry} material={materials['Material.002']} />
              <mesh geometry={nodes.Object_14.geometry} material={materials['Material.003']} />
            </group>
            <group position={[0.09, 1.74, -0.38]} scale={[0.02, 0.19, 0.02]}>
              <mesh geometry={nodes.Object_16.geometry} material={materials['Material.002']} />
              <mesh geometry={nodes.Object_17.geometry} material={materials['Material.003']} />
            </group>
            <group position={[-0.01, 1.06, 0]}>
              <mesh geometry={nodes.Object_19.geometry} material={materials['Material.001']} />
            </group>
            <group position={[-0.02, 1.36, 0.41]} rotation={[1.05, 0, 0]} scale={0.14}>
              <mesh geometry={nodes.Object_21.geometry} material={materials['Material.004']} />
            </group>
          </group>
          {/* <group position={[-1.04, -1.09, 0]} scale={31.48}>
            <mesh geometry={nodes.Object_23.geometry} material={materials.material_0} />
          </group> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bb8.gltf')
