/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alexus16 (https://sketchfab.com/Alexus16)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mazda-rx-7-fd-d35ff630df614771b82e7b2f59035b1e
title: Mazda RX-7 FD
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import useKeyPress from './useKeyPress'

export default function Model(props) {
  const upArrow = useKeyPress("ArrowUp")
  const downArrow = useKeyPress("ArrowDown")
  const rightArrow = useKeyPress("ArrowRight")
  const leftArrow = useKeyPress("ArrowLeft")
  const group = useRef()
  const wheel_front_right = useRef()
  const wheel_back_right = useRef()
  const wheel_front_left = useRef()
  const wheel_back_left = useRef()
  useFrame(() => {rightArrow && (wheel_front_right.current.rotation.x -= 40) || leftArrow && (wheel_front_right.current.rotation.x += 40)})
  useFrame(() => {rightArrow && (wheel_back_right.current.rotation.x -= 40) || leftArrow && (wheel_back_right.current.rotation.x += 40)})
  useFrame(() => {rightArrow && (wheel_front_left.current.rotation.x -= 40) || leftArrow && (wheel_front_left.current.rotation.x -= 40)})
  useFrame(() => {rightArrow && (wheel_back_left.current.rotation.x -= 40) || leftArrow && (wheel_back_left.current.rotation.x -= 40)})
  const { nodes, materials, animations } = useGLTF('/car.glb')
  const { actions } = useAnimations(animations, group)
  useFrame(() => {rightArrow && (group.current.position.x += 0.05)})
  useFrame(() => {leftArrow && (group.current.position.x -= 0.05)})
  return (
    <group ref={group} {...props} dispose={null}  position={[-7,2,2]} >
      <group rotation={[-Math.PI / 2, 0, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group name="Empty004_1" position={[2.05, -0.68, 1.91]} scale={[0.03, 0.03, 0.03]}>
            <group position={[-14.4, 0.34, -37]} rotation={[0.61, 0, 0]} scale={[1.334, 1.3, 1.4]}>
              <mesh castShadow geometry={nodes.mesh_0.geometry} material={materials['Material.002']} />
              <mesh castShadow geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
              <mesh castShadow geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
              <mesh castShadow geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
            </group>
          </group>
          {/* chassis */}
          <group position={[1.62, -0.71, 0.83]} rotation={[0.61, 0, 0]} scale={[0.04, 0.04, 0.04]}>
            <mesh castShadow geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
            <mesh castShadow geometry={nodes.mesh_5.geometry} material={materials['Material.003']} />
            <mesh castShadow geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
            <mesh castShadow geometry={nodes.mesh_7.geometry} material={materials['Material.008']} />
            <mesh castShadow geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
            <mesh castShadow geometry={nodes.mesh_9.geometry} material={materials['Material.016']} />
            <mesh castShadow geometry={nodes.mesh_10.geometry} material={materials['Material.017']} />
            <mesh castShadow geometry={nodes.mesh_11.geometry} material={materials['Material.018']} />
            <mesh castShadow geometry={nodes.mesh_12.geometry} material={materials['Material.019']} />
            <mesh castShadow geometry={nodes.mesh_13.geometry} material={materials.Material} />
          </group>
          <group position={[1.62, -0.71, 0.83]} rotation={[0.61, 0, 0]} scale={[0.04, 0.04, 0.04]}>
            <mesh castShadow geometry={nodes.mesh_14.geometry} material={nodes.mesh_14.material} />
            <mesh castShadow geometry={nodes.mesh_15.geometry} material={materials['Material.005']} />
          </group>
          <group position={[1.25, -0.96, -0.45]} rotation={[1.53, 0, 0]} scale={[0.03, 0.03, 0.03]}>
            <mesh castShadow geometry={nodes.mesh_16.geometry} material={nodes.mesh_16.material} />
          </group>
          {/* right front wheel */}
          <group ref={wheel_front_right} position={[1.08, -0.94, 1.71]} rotation={[6, 0, -Math.PI / 2]} scale={[0.17, 0.17, 0.17]}>
            <mesh castShadow geometry={nodes.mesh_17.geometry} material={nodes.mesh_17.material} />
            <mesh castShadow geometry={nodes.mesh_18.geometry} material={nodes.mesh_18.material} />
            <mesh castShadow geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} />
          </group>
          {/* left front wheel */}
          <group ref={wheel_front_left} position={[2.17, -0.94, 1.71]} rotation={[-0.63, 0, Math.PI / 2]} scale={[0.17, 0.17, 0.17]}>
            <mesh castShadow geometry={nodes.mesh_20.geometry} material={nodes.mesh_20.material} />
            <mesh castShadow geometry={nodes.mesh_21.geometry} material={nodes.mesh_21.material} />
            <mesh castShadow geometry={nodes.mesh_22.geometry} material={nodes.mesh_22.material} />
          </group>
          {/* right back wheel */}
          <group ref={wheel_back_right} position={[1.08, -0.94, 0.07]} rotation={[-2.51, 0, -Math.PI / 2]} scale={[0.17, 0.17, 0.17]}>
            <mesh castShadow geometry={nodes.mesh_23.geometry} material={nodes.mesh_23.material} />
            <mesh castShadow geometry={nodes.mesh_24.geometry} material={nodes.mesh_24.material} />
            <mesh castShadow geometry={nodes.mesh_25.geometry} material={nodes.mesh_25.material} />
          </group>
          {/* left back wheel */}
          <group ref={wheel_back_left} position={[2.17, -0.94, 0.07]} rotation={[-0.63, 0, Math.PI / 2]} scale={[0.17, 0.17, 0.17]}>
            <mesh castShadow geometry={nodes.mesh_26.geometry} material={nodes.mesh_26.material} />
            <mesh castShadow geometry={nodes.mesh_27.geometry} material={nodes.mesh_27.material} />
            <mesh castShadow geometry={nodes.mesh_28.geometry} material={nodes.mesh_28.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car.glb')
