/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: NT747 (https://sketchfab.com/ntdw)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/poe-dameron-x-wing-a7fd082a1ad54c32bacee493ddbc56df
title: Poe Dameron X wing
*/

import React, { useEffect, useRef,useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useUpdate } from '@react-three/fiber'
import { useScroll } from '../helpers/ScrollControls'

export default function Model({ ...props }) {
  const [prevPositions, setPrevPositions] = useState({ x: 0, y: 0 })
  const [positions, setPositions] = useState({ x: 0, y: 0 })
  useEffect(() => {
    setPrevPositions({
      x: positions.x,
      y: positions.y,
    })
    setPositions({
      x: props.cursorPosition.x,
      y: props.cursorPosition.y,
    })
  }, [props.cursorPosition])
  useFrame((state, delta) => {
    group.current.rotation.z += 0.001
    group.current.position.set(positions.x, positions.y, 0)
  })
  const group = useRef()
  const { nodes, materials } = useGLTF('/xwing.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.default_initialShadingGroup_0.geometry}
              material={materials.initialShadingGroup}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/xwing.gltf')
